### ISSUE TITLE
Update driver to lastest mongodb

### ISSUE THREAD

**Issue by x42en** [olegp/mongo-sync#29]
Hi!
Would it be possible to upgrade package.json (and client because test.js is failing then - mostly on getCollectionNames and addUser) to latest mongodb (3.4.14) or at least to latest 2.X version (2.2.35).
npm install is shouting: deprecated mongodb@2.0.24: Please upgrade to 2.2.19 or higher

Thanks a lot, and nice job for this lib!!

**Comment by olegp** [comment]
@x42en are you actually using common-node? Doesn't make much sense to use this lib without it and to be honest common-node is no longer the best solution for writing sync code in Node. You're much better off using Promises and async/await.

**Comment by x42en** [comment]
Thanks for your quick reply, actually we are using our own framework: https://github.com/x42en/IOServer

The reason is that's it let us make simple js class where all method (not starting by '_') are socket.io callable methods, which are run inside a Fiber... so I can code like I did in meteor without embedding all the crap I don't want... :D 

I can then simple files like below...

**Hosts.coffee:**

```coffee
DBConnector = require 'ioserver-mongodb'

module.exports = class Hosts
    constructor: () ->
        @db = new DBConnector
                host: 'localhost'
                db: 'test'

    insert: (data) ->
        @db.collection('hosts').insert(data)
    update: (uuid, data) ->
        if data._id?
            delete data._id
        @db.collection('hosts').update({"uuid": uuid}, data)
    find: (uuid) ->
        @db.collection('hosts').findOne({"uuid": uuid}, {"_id":0})
    remove: (uuid) ->
        @db.collection('hosts').remove({"uuid": uuid})
    rename: (uuid, name) ->
        @db.collection('hosts').update({"uuid": uuid},{"$set":{"human_name": name}})
    reset: ->
        @db.collection('hosts').remove({})
```

**Responder.coffee**
```coffee
module.exports = class Responder
    constructor: (@hosts) ->
        @hosts = new Hosts

    update_host: (socket, data) ->
        target = @hosts.find data.uuid
        
        unless target
            @hosts.insert data
        else
            @hosts.update data.uuid, data

        socket.emit 'updated', data.uuid
```

**Comment by olegp** [comment]
@x42en OK, understood. Can you send a pull request with the changes you propose? I can then merge and publish.

**Comment by x42en** [comment]
The problem is I am really poor at Vanilla JS :D and if i upgrade your package.json to latest version, unit tests are still failling (getCollectionNames() is now listCollections(), addUser must have role now, and the cursor.explain() is failing...)
I have tried to update your lib with proper modifications but I probably do it wrong cause I can not make it work :(

**Comment by x42en** [comment]
If you could transform your lib to coffee file I could probably take the lead to maintain the package if you want!

**Comment by olegp** [comment]
I don't have the bandwidth to do it myself unfortunately atm. If you send a PR I can review, accept and publish.
